[package]
name = "waycast"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.21.1"
glib = "0.21.1"
gtk = { version = "0.10.0", package = "gtk4" }
gtk4-layer-shell = "0.6.1"
relm4 = "0.10.0"
relm4-components = "0.10.0"
tracker = "0.2.2"
